name: Poems and Stories
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.9744537391234189
title: Writing by Ellis Reyes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3125
  lightness: 0.31542370445095
  saturation: 0.40174254844896495
  rhythmicContrast: 0.9455734738148749
purpose: []
